locations:
  - name: "кухня"
    paths: [ "коридор" ]
  - name: "коридор"
    paths: [ "кухня", "комната", "улица" ]
  - name: "комната"
    paths: [ "коридор" ]
    items:
      "на столе": [ "ключи", "конспекты", "рюкзак" ]
      "на полу": [ "носки" ]
  - name: "улица"
    paths: [ "коридор" ]
    aliases:
      "домой": "коридор"
from: "кухня"
